#!/usr/bin/env node
'use strict';
// Release lock for the agentctl mod (mods/agentctl). Claude Code caches an installed plugin by its
// version (~/.claude/plugins/cache/<marketplace>/agentctl/<version>/), so a change shipped under an
// unchanged version may never reach the people who already installed it. This records the mod's
// version together with a digest of its files, and CI fails when the two drift apart:
//   check   — the files match the recorded digest, or say what to do (bump, then update)
//   update  — record the current version and digest; refuses unless the version went up
// The digest is over the files that change what an installed mod does — everything git would ship
// except README.md and tests/, which a user's session never runs — read from disk, so the result is
// the same locally and in CI. A README-only or test-only change needs no release.

const { spawnSync } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const LOCK = 'release.json';
const SKIP_DIRS = new Set(['node_modules', '.claude']);
const SKIP_FILES = new Set([LOCK, '.DS_Store']);
const SKIP_PATHS = new Set(['README.md', 'tests']);

function listFiles(modDir) {
  const out = [];
  (function walk(rel) {
    for (const e of fs.readdirSync(path.join(modDir, rel), { withFileTypes: true })) {
      const p = rel ? `${rel}/${e.name}` : e.name;
      if (SKIP_PATHS.has(p)) continue;
      if (e.isDirectory()) {
        // `.claude-plugin/types/` is generated by the host (the mod's .gitignore excludes it).
        if (SKIP_DIRS.has(e.name) || p === '.claude-plugin/types') continue;
        walk(p);
      } else if (e.isFile() && !SKIP_FILES.has(e.name)) out.push(p);
    }
  })('');
  return out.sort();
}

function digest(modDir) {
  const h = crypto.createHash('sha256');
  for (const p of listFiles(modDir)) {
    h.update(p).update('\0').update(fs.readFileSync(path.join(modDir, p))).update('\0');
  }
  return h.digest('hex');
}

function versionOf(modDir) {
  return JSON.parse(fs.readFileSync(path.join(modDir, '.claude-plugin', 'plugin.json'), 'utf8')).version;
}

function readLock(modDir) {
  try {
    return JSON.parse(fs.readFileSync(path.join(modDir, LOCK), 'utf8'));
  } catch {
    return null;
  }
}

// a > b for dotted numeric versions; a pre-release suffix is ignored for ordering.
function newer(a, b) {
  const p = (v) => String(v).split('-')[0].split('.').map(Number);
  const x = p(a), y = p(b);
  for (let i = 0; i < Math.max(x.length, y.length); i++) {
    if ((x[i] || 0) !== (y[i] || 0)) return (x[i] || 0) > (y[i] || 0);
  }
  return false;
}

// base: the lock as it was at the comparison point (the PR base, the previous main commit, or the last
// agentctl-v tag), or null when the mod did not exist there. Without it the lock only proves itself:
// a commit that changes the code and rewrites the digest by hand, version unchanged, would pass.
function check(modDir, { base = null } = {}) {
  const lock = readLock(modDir);
  const version = versionOf(modDir);
  const current = digest(modDir);
  if (!lock) return { ok: false, message: `${LOCK} is missing; run: node .github/scripts/agentctl-version.js update` };
  if (lock.digest === current && lock.version === version) {
    if (base && base.digest !== current && !newer(version, base.version)) {
      return { ok: false, message: `mods/agentctl changed since ${base.ref} but its version ${version} is not newer than ${base.version} there: bump "version" in mods/agentctl/.claude-plugin/plugin.json, then run: node .github/scripts/agentctl-version.js update` };
    }
    return { ok: true, version };
  }
  if (version === lock.version) {
    return { ok: false, message: `mods/agentctl changed but its version is still ${version}: bump "version" in mods/agentctl/.claude-plugin/plugin.json, then run: node .github/scripts/agentctl-version.js update` };
  }
  return { ok: false, message: `mods/agentctl is at ${version} but ${LOCK} records ${lock.version}: run: node .github/scripts/agentctl-version.js update` };
}

function update(modDir) {
  const lock = readLock(modDir);
  const version = versionOf(modDir);
  const current = digest(modDir);
  if (lock && lock.digest === current && lock.version === version) return { ok: true, version, written: false };
  if (lock && !newer(version, lock.version)) {
    return { ok: false, message: `version ${version} is not newer than the recorded ${lock.version}; bump it first` };
  }
  fs.writeFileSync(path.join(modDir, LOCK), JSON.stringify({ version, digest: current }, null, 2) + '\n');
  return { ok: true, version, written: true };
}

// The lock at a git ref, read from the repository: null when the mod (or its lock) did not exist at
// that ref; an error when the ref itself cannot be resolved — a comparison that cannot be made is a
// failure, never a pass.
function lockAt(repoRoot, ref) {
  const git = (args) => spawnSync('git', ['-C', repoRoot, ...args], { encoding: 'utf8' });
  if (git(['rev-parse', '--verify', '--quiet', `${ref}^{commit}`]).status !== 0) return { error: `cannot resolve ${ref}` };
  const r = git(['show', `${ref}:mods/agentctl/${LOCK}`]);
  if (r.status !== 0) return { lock: null };
  try {
    return { lock: { ...JSON.parse(r.stdout), ref } };
  } catch {
    return { error: `${LOCK} at ${ref} is not valid JSON` };
  }
}

module.exports = { check, update, digest, listFiles, newer, lockAt };

if (require.main === module) {
  const modDir = path.resolve(__dirname, '../../mods/agentctl');
  const [cmd, flag, ref] = process.argv.slice(2);
  let r;
  if (cmd === 'check') {
    let base = null;
    if (flag === '--base') {
      const at = ref ? lockAt(path.resolve(__dirname, '../..'), ref) : { error: '--base needs a git ref' };
      base = at.lock;
      r = at.error ? { ok: false, message: at.error } : null;
    }
    r = r || check(modDir, { base });
  } else if (cmd === 'update') r = update(modDir);
  else r = { ok: false, message: 'usage: agentctl-version.js check [--base <git ref>] | update' };
  process.stdout.write((r.ok ? `agentctl ${r.version}${r.written ? ' recorded' : ' ok'}` : r.message) + '\n');
  process.exit(r.ok ? 0 : 1);
}
